//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int id { get; set; }
        public decimal price { get; set; }
        public decimal tax { get; set; }
        public int qty { get; set; }
        public int bill_Id { get; set; }
        public int products_Id { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Products Products { get; set; }
    }
}
