//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.BillDetail = new HashSet<BillDetail>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public decimal tax { get; set; }
        public decimal discount { get; set; }
        public string paymentType { get; set; }
        public string state { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
        public int employee_Id { get; set; }
        public int client_Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<BillDetail> BillDetail { get; set; }
    }
}
