//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.BillDetail = new HashSet<BillDetail>();
            this.ProductSuppliers = new HashSet<ProductSuppliers>();
            this.WarehouseProducts = new HashSet<WarehouseProducts>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int code { get; set; }
        public decimal costPrice { get; set; }
        public int category_Id { get; set; }
        public int brand_Id { get; set; }
    
        public virtual ICollection<BillDetail> BillDetail { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<ProductSuppliers> ProductSuppliers { get; set; }
        public virtual ICollection<WarehouseProducts> WarehouseProducts { get; set; }
    }
}
