//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseProducts
    {
        public int id { get; set; }
        public int qtyAvailable { get; set; }
        public int idWarehouse { get; set; }
        public int idProducts { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
